version: "3.8"
services:
  backend:
    image: backend:latest
    build: ./backend
    ports:
    - target: 5001
      published: 5001
  database:
    image: mysql:latest
    container_name: mysql
    ports:
    - target: 3306
      published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      SECRET_KEY: test
  frontend:
    image: frontend:latest
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
  nginx:
    image: nginx:latest
    ports:
    - target: 85
      published: 85
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

